version: '3.4'

services:
  cleanarchsample.api:
    image: ${DOCKER_REGISTRY-}cleanarchsampleapi
    build:
      context: .
      dockerfile: Presentation/CleanArchSample.Api/Dockerfile
    depends_on:
      - mssql
      - rabbitmq
    networks:
      - mynetwork

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "QiI9Kskpyy"
        ACCEPT_EULA: "Y"
    ports:
        - "1434:1433"
    volumes:
        - mssql-data:/var/opt/mssql
    networks:
      - mynetwork

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mynetwork

  redis:
    image: "redis:latest"
    ports:
    - "6379:6379"
    networks:
    - mynetwork

volumes:
    mssql-data:

networks:
  mynetwork:
    driver: bridge
